"""indexer: channel chat id and finalized_at

Additive, both columns nullable, no backfill needed -- `products` is still empty
because CP7 built the schema and nothing wrote to it.

channel_chat_id  WHICH channel the post came from. copyMessage needs a
                 from_chat_id, so CP9 would otherwise have to read the channel
                 out of config and trust it never changed.
finalized_at     NULL until an album has settled and its caption is parsed.
                 indexed_at cannot carry this: it is NOT NULL with a server
                 default, so it is stamped the moment the row appears.

Revision ID: 20acdd5fa0a1
Revises: acd5c8bdb525
Create Date: 2026-09-04 22:26:28.235238
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20acdd5fa0a1"
down_revision: str | None = "acd5c8bdb525"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("channel_chat_id", sa.BigInteger(), nullable=True))
    op.add_column("products", sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(
        op.f("ck_products_only_channel_rows_have_a_chat_id"),
        "products",
        "(source = 'channel') OR (channel_chat_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_products_only_channel_rows_have_a_chat_id"), "products", type_="check"
    )
    op.drop_column("products", "finalized_at")
    op.drop_column("products", "channel_chat_id")
    # ### end Alembic commands ###
