"""orders, order reminders, ping offsets

ORDER IS LOAD-BEARING and autogenerate got it wrong, exactly as it did at CP5.
`orders` carries a composite FK to `recipients(id, shop_id)`, so the UNIQUE that
FK targets has to exist BEFORE the table -- autogenerate emitted it after, which
fails on a fresh database while passing on a developer's, where the tables
already exist. The downgrade is the mirror: drop the tables first, then the
constraint they depend on.

Everything else here is additive. `shops.order_ping_offset_hours` is an ARRAY to
match `reminder_offsets` rather than introducing a second convention.

Revision ID: 75e0e9cdd766
Revises: 20acdd5fa0a1
Create Date: 2026-09-06 00:03:46.525374
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "75e0e9cdd766"
down_revision: str | None = "20acdd5fa0a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # FIRST: orders' composite FK targets this. See the module docstring.
    op.create_unique_constraint(op.f("uq_recipients_id_shop_id"), "recipients", ["id", "shop_id"])
    op.create_table(
        "orders",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("recipient_id", sa.BigInteger(), nullable=True),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("product_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("price_uzs_snapshot", sa.BigInteger(), nullable=True),
        sa.Column("telegram_file_id_snapshot", sa.Text(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("delivery_hour", sa.Time(), nullable=False),
        sa.Column("delivery_location_text", sa.Text(), nullable=True),
        sa.Column("delivery_location_lat", sa.Float(), nullable=True),
        sa.Column("delivery_location_lon", sa.Float(), nullable=True),
        sa.Column("landmark", sa.String(length=200), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'placed'"), nullable=False
        ),
        sa.Column("submit_token", sa.String(length=32), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('placed', 'confirmed', 'delivered', 'rejected', 'cancelled')",
            name=op.f("ck_orders_status_known"),
        ),
        sa.CheckConstraint(
            "(delivery_location_lat IS NULL) = (delivery_location_lon IS NULL)",
            name=op.f("ck_orders_coordinates_come_in_pairs"),
        ),
        sa.CheckConstraint(
            "(delivery_location_text IS NOT NULL) <> (delivery_location_lat IS NOT NULL)",
            name=op.f("ck_orders_exactly_one_location"),
        ),
        sa.CheckConstraint(
            "price_uzs_snapshot IS NULL OR price_uzs_snapshot > 0",
            name=op.f("ck_orders_snapshot_price_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "shop_id"],
            ["customers.id", "customers.shop_id"],
            name=op.f("fk_orders_customer_id_shop_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "shop_id"],
            ["products.id", "products.shop_id"],
            name=op.f("fk_orders_product_id_shop_id_products"),
            # Column-scoped. A bare SET NULL on a COMPOSITE key nulls every
            # referencing column, which here includes shop_id (NOT NULL), so
            # deleting a product would fail and take the indexer down with it.
            ondelete="SET NULL (product_id)",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id", "shop_id"],
            ["recipients.id", "recipients.shop_id"],
            name=op.f("fk_orders_recipient_id_shop_id_recipients"),
            ondelete="SET NULL (recipient_id)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("id", "shop_id", name=op.f("uq_orders_id_shop_id")),
        # The single-flight guard: two concurrent submits of one confirmation
        # screen collide here instead of both inserting.
        sa.UniqueConstraint("shop_id", "submit_token", name=op.f("uq_orders_shop_id_submit_token")),
    )
    op.create_index("ix_orders_customer", "orders", ["customer_id"], unique=False)
    op.create_index(
        "ix_orders_shop_delivery_date", "orders", ["shop_id", "delivery_date"], unique=False
    )
    op.create_table(
        "order_reminders",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("ping_number", sa.SmallInteger(), nullable=False),
        sa.Column("due_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "state", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "state IN ('pending', 'sent', 'failed', 'dead_letter')",
            name=op.f("ck_order_reminders_state_known"),
        ),
        sa.CheckConstraint("ping_number > 0", name=op.f("ck_order_reminders_ping_number_positive")),
        sa.ForeignKeyConstraint(
            ["order_id", "shop_id"],
            ["orders.id", "orders.shop_id"],
            name=op.f("fk_order_reminders_order_id_shop_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_reminders")),
        sa.UniqueConstraint(
            "order_id", "ping_number", name=op.f("uq_order_reminders_order_id_ping_number")
        ),
    )
    op.create_index(
        "ix_order_reminders_due", "order_reminders", ["state", "due_at_utc"], unique=False
    )
    op.add_column(
        "shops",
        sa.Column(
            "order_ping_offset_hours",
            postgresql.ARRAY(sa.Integer()),
            server_default=sa.text("'{3,1}'::integer[]"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "order_ping_offset_hours")
    op.drop_index("ix_order_reminders_due", table_name="order_reminders")
    op.drop_table("order_reminders")
    op.drop_index("ix_orders_shop_delivery_date", table_name="orders")
    op.drop_index("ix_orders_customer", table_name="orders")
    op.drop_table("orders")
    # LAST: both tables' foreign keys had to go before their target.
    op.drop_constraint(op.f("uq_recipients_id_shop_id"), "recipients", type_="unique")
    # ### end Alembic commands ###
