"""message log ledger and extended notification states

Revision ID: 9c82f8b5d486
Revises: ae2ff6902099
Create Date: 2026-09-04 07:29:09.279484
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9c82f8b5d486"
down_revision: str | None = "ae2ff6902099"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_log",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("template_key", sa.String(length=64), nullable=False),
        sa.Column("transition_key", sa.String(length=160), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'claimed'"), nullable=False
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "claimed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.CheckConstraint("channel IN ('telegram')", name=op.f("ck_message_log_channel_known")),
        sa.CheckConstraint(
            "status = 'claimed' OR resolved_at IS NOT NULL",
            name=op.f("ck_message_log_resolved_needs_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('claimed', 'sent', 'failed', 'cancelled')",
            name=op.f("ck_message_log_status_known"),
        ),
        sa.CheckConstraint("attempts >= 1", name=op.f("ck_message_log_attempts_at_least_one")),
        sa.ForeignKeyConstraint(
            ["customer_id", "shop_id"],
            ["customers.id", "customers.shop_id"],
            name=op.f("fk_message_log_customer_id_shop_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_log")),
        sa.UniqueConstraint(
            "customer_id",
            "template_key",
            "transition_key",
            name=op.f("uq_message_log_customer_id_template_key_transition_key"),
        ),
    )
    # Autogenerate did NOT detect this: the constraint NAME is unchanged and only
    # the expression differs, which its comparison does not look at. Written by
    # hand. Extending a text+CHECK enum is the documented pattern in
    # CONTRIBUTING.md -- drop the old constraint, add the widened one.
    op.drop_constraint("ck_scheduled_notifications_state_known", "scheduled_notifications")
    op.create_check_constraint(
        "state_known",
        "scheduled_notifications",
        "state IN ('pending', 'sent', 'failed', 'expired', 'cancelled', 'dead_letter')",
    )
    op.create_index("ix_message_log_stuck", "message_log", ["status", "claimed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_message_log_stuck", table_name="message_log")
    op.drop_table("message_log")
    # ### end Alembic commands ###
