"""occasions and consent events

Revision ID: a87cd107a0ed
Revises: b88b5a0d77db
Create Date: 2026-09-03 16:39:10.746760
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a87cd107a0ed"
down_revision: str | None = "b88b5a0d77db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_events",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("text_version", sa.String(length=32), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "source IN ('first_occasion', 'settings')", name=op.f("ck_consent_events_source_known")
        ),
        sa.CheckConstraint("type IN ('store_dates')", name=op.f("ck_consent_events_type_known")),
        sa.ForeignKeyConstraint(
            ["customer_id", "shop_id"],
            ["customers.id", "customers.shop_id"],
            name=op.f("fk_consent_events_customer_id_shop_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_events")),
    )
    op.create_index(
        "ix_consent_events_customer_type", "consent_events", ["customer_id", "type"], unique=False
    )
    op.create_table(
        "occasions",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("month", sa.SmallInteger(), nullable=False),
        sa.Column("day", sa.SmallInteger(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('wife', 'spouse', 'mother', 'father', 'child', 'friend', 'custom')",
            name=op.f("ck_occasions_type_known"),
        ),
        sa.CheckConstraint(
            "day <= CASE month WHEN 1 THEN 31 WHEN 2 THEN 29 WHEN 3 THEN 31 WHEN 4 THEN 30 WHEN 5 THEN 31 WHEN 6 THEN 30 WHEN 7 THEN 31 WHEN 8 THEN 31 WHEN 9 THEN 30 WHEN 10 THEN 31 WHEN 11 THEN 30 WHEN 12 THEN 31 END",
            name=op.f("ck_occasions_day_matches_month"),
        ),
        sa.CheckConstraint("day BETWEEN 1 AND 31", name=op.f("ck_occasions_day_range")),
        sa.CheckConstraint("length(btrim(label)) > 0", name=op.f("ck_occasions_label_not_blank")),
        sa.CheckConstraint("month BETWEEN 1 AND 12", name=op.f("ck_occasions_month_range")),
        sa.CheckConstraint(
            "year IS NULL OR NOT (month = 2 AND day = 29) OR (mod(year, 4) = 0 AND (mod(year, 100) <> 0 OR mod(year, 400) = 0))",
            name=op.f("ck_occasions_feb29_needs_leap_year"),
        ),
        sa.CheckConstraint(
            "year IS NULL OR year BETWEEN 1900 AND 2100", name=op.f("ck_occasions_year_range")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "shop_id"],
            ["customers.id", "customers.shop_id"],
            name=op.f("fk_occasions_customer_id_shop_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_occasions")),
        sa.UniqueConstraint(
            "customer_id",
            "month",
            "day",
            "label",
            name=op.f("uq_occasions_customer_id_month_day_label"),
        ),
    )
    op.create_index(
        "ix_occasions_customer_active", "occasions", ["customer_id", "active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_occasions_customer_active", table_name="occasions")
    op.drop_table("occasions")
    op.drop_index("ix_consent_events_customer_type", table_name="consent_events")
    op.drop_table("consent_events")
    # ### end Alembic commands ###
