"""catalog: products, hashtags, aliases

Revision ID: acd5c8bdb525
Revises: 7537908ffb89
Create Date: 2026-09-04 17:00:31.413736
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "acd5c8bdb525"
down_revision: str | None = "7537908ffb89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashtag_aliases",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("alias_normalized", sa.String(length=64), nullable=False),
        sa.Column("canonical_hashtag", sa.String(length=64), nullable=False),
        sa.Column("fixture_version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "alias_normalized <> canonical_hashtag",
            name=op.f("ck_hashtag_aliases_alias_differs_from_canonical"),
        ),
        sa.CheckConstraint(
            "length(alias_normalized) > 0", name=op.f("ck_hashtag_aliases_alias_not_blank")
        ),
        sa.CheckConstraint(
            "length(canonical_hashtag) > 0", name=op.f("ck_hashtag_aliases_canonical_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"],
            ["shops.id"],
            name=op.f("fk_hashtag_aliases_shop_id_shops"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hashtag_aliases")),
        sa.UniqueConstraint(
            "shop_id", "alias_normalized", name=op.f("uq_hashtag_aliases_shop_id_alias_normalized")
        ),
    )
    op.create_index(
        "ix_hashtag_aliases_lookup",
        "hashtag_aliases",
        ["shop_id", "alias_normalized"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("price_uzs", sa.BigInteger(), nullable=True),
        sa.Column(
            "price_confidence",
            sa.String(length=8),
            server_default=sa.text("'none'"),
            nullable=False,
        ),
        sa.Column("telegram_file_id", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("channel_message_id", sa.BigInteger(), nullable=True),
        sa.Column("media_group_id", sa.String(length=64), nullable=True),
        sa.Column("caption_raw", sa.Text(), nullable=True),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(price_uzs IS NULL) = (price_confidence = 'none')",
            name=op.f("ck_products_price_matches_confidence"),
        ),
        sa.CheckConstraint(
            "(source = 'channel') OR (channel_message_id IS NULL)",
            name=op.f("ck_products_only_channel_rows_have_a_message_id"),
        ),
        sa.CheckConstraint(
            "price_confidence IN ('high', 'medium', 'none')",
            name=op.f("ck_products_price_confidence_known"),
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'channel')", name=op.f("ck_products_source_known")
        ),
        sa.CheckConstraint(
            "price_uzs IS NULL OR price_uzs > 0", name=op.f("ck_products_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_products_shop_id_shops"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("id", "shop_id", name=op.f("uq_products_id_shop_id")),
        sa.UniqueConstraint(
            "shop_id", "channel_message_id", name=op.f("uq_products_shop_id_channel_message_id")
        ),
    )
    op.create_index("ix_products_shop_active", "products", ["shop_id", "active"], unique=False)
    op.create_index(
        "uq_products_shop_media_group",
        "products",
        ["shop_id", "media_group_id"],
        unique=True,
        postgresql_where=sa.text("media_group_id IS NOT NULL"),
    )
    op.create_table(
        "product_hashtags",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("hashtag_normalized", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "length(hashtag_normalized) > 0", name=op.f("ck_product_hashtags_hashtag_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["product_id", "shop_id"],
            ["products.id", "products.shop_id"],
            name=op.f("fk_product_hashtags_product_id_shop_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_hashtags")),
        sa.UniqueConstraint(
            "product_id",
            "hashtag_normalized",
            name=op.f("uq_product_hashtags_product_id_hashtag_normalized"),
        ),
    )
    op.create_index(
        "ix_product_hashtags_lookup",
        "product_hashtags",
        ["shop_id", "hashtag_normalized"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_hashtags_lookup", table_name="product_hashtags")
    op.drop_table("product_hashtags")
    op.drop_index(
        "uq_products_shop_media_group",
        table_name="products",
        postgresql_where=sa.text("media_group_id IS NOT NULL"),
    )
    op.drop_index("ix_products_shop_active", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_hashtag_aliases_lookup", table_name="hashtag_aliases")
    op.drop_table("hashtag_aliases")
    # ### end Alembic commands ###
