"""scheduled notifications and shop default send time

Revision ID: ae2ff6902099
Revises: b9083858d3ef
Create Date: 2026-09-04 03:39:14.692438
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ae2ff6902099"
down_revision: str | None = "b9083858d3ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MUST precede the table: the composite FK below references
    # (occasions.id, occasions.shop_id), and Postgres refuses a foreign key
    # with no matching unique constraint on the referenced table.
    op.create_unique_constraint(op.f("uq_occasions_id_shop_id"), "occasions", ["id", "shop_id"])
    op.create_table(
        "scheduled_notifications",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column("occasion_id", sa.BigInteger(), nullable=False),
        sa.Column("occurrence_year", sa.Integer(), nullable=False),
        sa.Column("offset_days", sa.SmallInteger(), nullable=False),
        sa.Column("due_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column(
            "state", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merge_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            "channel IN ('telegram')", name=op.f("ck_scheduled_notifications_channel_known")
        ),
        sa.CheckConstraint(
            "state <> 'sent' OR sent_at IS NOT NULL",
            name=op.f("ck_scheduled_notifications_sent_needs_timestamp"),
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'sent', 'failed', 'expired')",
            name=op.f("ck_scheduled_notifications_state_known"),
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_scheduled_notifications_attempts_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "shop_id"],
            ["customers.id", "customers.shop_id"],
            name=op.f("fk_scheduled_notifications_customer_id_shop_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["occasion_id", "shop_id"],
            ["occasions.id", "occasions.shop_id"],
            name=op.f("fk_scheduled_notifications_occasion_id_shop_id_occasions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_notifications")),
        sa.UniqueConstraint(
            "occasion_id",
            "occurrence_year",
            "offset_days",
            "channel",
            name=op.f("uq_scheduled_notifications_occasion_id_occurrence_year_offset_days_channel"),
        ),
    )
    op.create_index(
        "ix_scheduled_notifications_customer_state",
        "scheduled_notifications",
        ["customer_id", "state"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_notifications_due",
        "scheduled_notifications",
        ["state", "due_at_utc"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_notifications_merge_key",
        "scheduled_notifications",
        ["merge_key"],
        unique=False,
    )
    op.add_column(
        "shops",
        sa.Column("default_send_time", sa.Time(), server_default=sa.text("'20:00'"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shops", "default_send_time")
    op.drop_index("ix_scheduled_notifications_merge_key", table_name="scheduled_notifications")
    op.drop_index("ix_scheduled_notifications_due", table_name="scheduled_notifications")
    op.drop_index("ix_scheduled_notifications_customer_state", table_name="scheduled_notifications")
    op.drop_table("scheduled_notifications")
    # MUST follow the table: the composite FK depends on this unique constraint,
    # so Postgres refuses to drop it while scheduled_notifications still exists.
    op.drop_constraint(op.f("uq_occasions_id_shop_id"), "occasions", type_="unique")
    # ### end Alembic commands ###
