"""shops and customers

Revision ID: b88b5a0d77db
Revises:
Create Date: 2026-09-03 15:45:34.121934
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b88b5a0d77db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shops",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "timezone",
            sa.String(length=64),
            server_default=sa.text("'Asia/Tashkent'"),
            nullable=False,
        ),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("group_chat_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "owner_telegram_ids",
            postgresql.ARRAY(sa.BigInteger()),
            server_default=sa.text("'{}'::bigint[]"),
            nullable=False,
        ),
        sa.Column("working_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("same_day_cutoff", sa.Time(), server_default=sa.text("'18:00'"), nullable=False),
        sa.Column(
            "min_lead_time_minutes", sa.Integer(), server_default=sa.text("180"), nullable=False
        ),
        sa.Column("daily_order_cap", sa.Integer(), nullable=True),
        sa.Column(
            "reminder_offsets",
            postgresql.ARRAY(sa.SmallInteger()),
            server_default=sa.text("'{-7,-1,0}'::smallint[]"),
            nullable=False,
        ),
        sa.Column(
            "reminder_weekly_cap", sa.SmallInteger(), server_default=sa.text("4"), nullable=False
        ),
        sa.Column(
            "reminder_merge_window_days",
            sa.SmallInteger(),
            server_default=sa.text("2"),
            nullable=False,
        ),
        sa.Column(
            "peak_pending_threshold", sa.Integer(), server_default=sa.text("15"), nullable=False
        ),
        sa.Column(
            "peak_hourly_threshold", sa.Integer(), server_default=sa.text("40"), nullable=False
        ),
        sa.Column(
            "peak_manual_override", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shops")),
    )
    op.create_table(
        "customers",
        sa.Column("shop_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("phone_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("lang", sa.String(length=2), server_default=sa.text("'uz'"), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("lang IN ('uz', 'ru')", name=op.f("ck_customers_lang_known")),
        sa.CheckConstraint(
            "status IN ('active', 'blocked', 'stopped')", name=op.f("ck_customers_status_known")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_customers_shop_id_shops"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("id", "shop_id", name=op.f("uq_customers_id_shop_id")),
        sa.UniqueConstraint(
            "shop_id", "telegram_user_id", name=op.f("uq_customers_shop_id_telegram_user_id")
        ),
    )
    op.create_index(op.f("ix_customers_shop_id"), "customers", ["shop_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customers_shop_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_table("shops")
    # ### end Alembic commands ###
