"""reminder preferences and flower preset

Revision ID: b9083858d3ef
Revises: 6a4f76c77864
Create Date: 2026-09-03 22:50:14.657095
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b9083858d3ef"
down_revision: str | None = "6a4f76c77864"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("reminder_count", sa.SmallInteger(), nullable=True))
    op.add_column("customers", sa.Column("preferred_send_time", sa.Time(), nullable=True))
    op.create_check_constraint(
        op.f("ck_customers_preferred_send_time_known"),
        "customers",
        "preferred_send_time IS NULL OR preferred_send_time IN ('09:00', '13:00', '20:00')",
    )
    op.create_check_constraint(
        op.f("ck_customers_reminder_count_known"),
        "customers",
        "reminder_count IS NULL OR reminder_count IN (1, 2, 3)",
    )
    op.create_check_constraint(
        op.f("ck_recipients_preferred_hashtag_known"),
        "recipients",
        "preferred_hashtag IS NULL OR preferred_hashtag IN ('atirgul', 'tyulpan', 'lola')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_recipients_preferred_hashtag_known"), "recipients", type_="check")
    op.drop_constraint(op.f("ck_customers_reminder_count_known"), "customers", type_="check")
    op.drop_constraint(op.f("ck_customers_preferred_send_time_known"), "customers", type_="check")
    op.drop_column("customers", "preferred_send_time")
    op.drop_column("customers", "reminder_count")
    # ### end Alembic commands ###
